routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

	if ( Auth::check() ) {

		return redirect('home');

	} else {

		return view('welcome');
	}
});

Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'verify' => false, // Email Verification Routes...
]);

Route::get('home', 'HomeController@index')->name('home');
Route::get('img/{filename}', 'HomeController@img')->name('img');
Route::get('exam/{id}', 'HomeController@exam')->name('exam');
Route::post('answer', 'HomeController@save_answer')->name('answer');
Route::post('final', 'HomeController@submit_answers')->name('final');

Route::resources([
    'exams' => 'ExamsController',
    'users' => 'UsersController',
    'questions' => 'QuestionsController',
    'results' => 'ResultsController',
]);

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Result;
use Auth;

class Exam extends Model
{
    protected $fillable = [
        'name', 'time_limit', 'user_id', 'instructions'
    ];

    public function isCompleted()
    {
    	return Result::where([
    		['user_id','=', Auth::user()->id],
    		['exam_id','=', $this->id],
    		['status','=', 'completed'],
    	])->count();
    }

    public function result()
    {
    	return Result::where([
    		['user_id','=', Auth::user()->id],
    		['exam_id','=', $this->id]
    	])->first();
    }
}

app/Http/Controllers/ExamsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Question;
use App\Exam;
use Validator;
use Storage;
use Auth;

class ExamsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','role:teacher,admin']);
        $this->validation = [
            'name' => 'required|string|max:255',
            'time_limit' => 'required|integer|max:255',
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $params['exams'] = Exam::paginate(10);
        return view('exam.index',$params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('exam.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Input validation
        $validator = Validator::make( $request->all(), $this->validation );

        if( $validator->fails() ) 
        {
            return redirect('exams/create')->with('error', $validator->messages());
        }

        $exam = new Exam;
        $exam->fill( $request->all() );
        $exam->user_id = Auth::user()->id;
        $exam->save();

        return redirect('exams')->with('success','Exam succesfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $params['exam'] = Exam::find($id);

        if (!$params['exam']) {
            return redirect('exams')->with('error','Exam no longer exist.');
        }

        $params['questions'] = Question::where('exam_id','=',$id)->paginate(10);

        return view('exam.show',$params);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $params['exam'] = Exam::find($id);

        if (!$params['exam']) {
            return redirect('exams')->with('error','Exam no longer exist.');
        }

        return view('exam.edit',$params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $exam = Exam::find($id);

        if (!$exam) {
            return redirect('exams')->with('error','Exam no longer exist.');
        }
        
        // Input validation
        $validator = Validator::make( $request->all(), $this->validation );

        if( $validator->fails() ) 
        {
            return redirect('exams/'.$id.'/edit')->with('error', $validator->messages());
        }

        $exam->fill( $request->all() );
        $exam->user_id = Auth::user()->id;
        $exam->save();

        return redirect('exams/'.$id.'/edit')->with('success','Exam succesfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $exam = Exam::find($id);

        $questions = Question::where('exam_id','=',$exam->id)->get();

        if ( $questions->count() ) 
        {
            foreach ($questions as $question) 
            {
                $img_a = json_decode( $question->a );
                $img_b = json_decode( $question->b );
                $img_c = json_decode( $question->c );
                $img_d = json_decode( $question->d );

                if ( isset($img_a->image) && Storage::exists('public/'.$img_a->image) ) { 
                    Storage::delete('public/'.$img_a->image);    
                }

                if ( isset($img_b->image) && Storage::exists('public/'.$img_b->image) ) { 
                    Storage::delete('public/'.$img_b->image);    
                }

                if ( isset($img_c->image) && Storage::exists('public/'.$img_c->image) ) { 
                    Storage::delete('public/'.$img_c->image);    
                }

                if ( isset($img_d->image) && Storage::exists('public/'.$img_d->image) ) { 
                    Storage::delete('public/'.$img_d->image);    
                }

                $question->delete();
            }
        }

        if (!$exam) {
            return redirect('exams')->with('error','Exam no longer exist.');
        }

        $exam->delete();

        return redirect('exams')->with('success','Exam successfully removed.');
    }
}

resources/views/exam/create.blade.php
@extends('home')
@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Create Exam</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('exams.index') }}">Exams</a></li>
            <li class="breadcrumb-item active">Create Exam</li>
        </ol>
    </div>
</main>
<div class="container-fluid">
	<div class="card">
		<h5 class="card-header">
			Exam details
		</h5>
		<div class="card-body">
			
			<form action="{{ route('exams.store') }}" method="POST" role="form">
				@csrf
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="exam-name">Name:</label>
							<input type="text" class="form-control" required id="exam-name" name="name">
							@error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="exam-duration">Exam Duration (minutes):</label>
							<input type="number" value="60" class="form-control" id="exam-duration" required name="time_limit" placeholder="60">
							@error('time_limit')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="exam-instructions">Exam Instructions:</label>
					<textarea rows="5" class="form-control" required id="exam-instructions" name="instructions"></textarea>
					@error('instructions')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
				</div>
				<button type="submit" class="btn btn-primary">Save &nbsp;<i class="fa fa-save"></i></button>
			</form>

		</div>
	</div>
</div>
@endsection

resources/views/exam/edit.blade.php
@extends('home')
@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Edit Exams</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('exams.index') }}">Exams</a></li>
            <li class="breadcrumb-item active">Edit Exam</li>
        </ol>
    </div>
</main>
<div class="container-fluid">
	<div class="card">
		<h5 class="card-header">
			Exam details
		</h5>
		<div class="card-body">
			
			<form action="{{ route('exams.update',$exam->id) }}" method="POST" role="form">
				@csrf
				<input type="hidden" name="_method" value="PUT">
				<div class="row">
					<div class="col">
						<div class="form-group">
							<label for="exam-name">Name:</label>
							<input type="text" class="form-control" required id="exam-name" name="name" value="{{ $exam->name }}">
							@error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
						</div>
					</div>
					<div class="col">
						<div class="form-group">
							<label for="exam-duration">Exam Duration (minutes):</label>
							<input type="number" value="{{ $exam->time_limit }}" class="form-control" id="exam-duration" required name="time_limit" placeholder="60">
							@error('time_limit')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="exam-instructions">Exam Instructions:</label>
					<textarea rows="5" class="form-control" required id="exam-instructions" name="instructions">{{ $exam->instructions }}</textarea>
					@error('instructions')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
				</div>
				<button type="submit" class="btn btn-primary">Save &nbsp;<i class="fa fa-save"></i></button>
			</form>

		</div>
	</div>
</div>
@endsection

resources/views/exam/index.blade.php
@extends('home')
@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Exam</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
            <li class="breadcrumb-item active">Exam lists</li>
        </ol>
    </div>
</main>
<div class="container-fluid">
	<div class="card">
		<h5 class="card-header">
			Lists <a href="{{ route('exams.create') }}" class="btn btn-info btn-sm float-right">Create Exam <i class="fa fa-plus"></i></a>
		</h5>
		<div class="card-body">
			
			@if($exams->count())

			<table class="table table-hover table-bordered">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Name</th>
						<th scope="col">Duration</th>
						<th scope="col" class="text-right">Options</th>
					</tr>
				</thead>
				<tbody>
					@foreach($exams as $exam)
					<tr>
						<td>{{ $exam->name }}</td>
						<td>{{ $exam->time_limit }} minutes</td>
						<td>
							<div class="float-right">
								<a href="{{ route('exams.edit',$exam->id) }}" class="btn btn-sm btn-success">
									Edit <i class="fa fa-edit"></i>
								</a>
								
								<a href="{{ route('results.index',['exam'=>$exam->id]) }}" class="btn btn-sm btn-info">
									View Results <i class="fa fa-eye"></i>
								</a>
								
								<a href="{{ route('exams.show',$exam->id) }}" class="btn btn-sm btn-primary">
									View Questions <i class="fa fa-eye"></i>
								</a>

								<button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#deleteModal-{{$exam->id}}">
									Delete <i class="fa fa-times"></i>
								</button>

								<div class="modal fade" id="deleteModal-{{$exam->id}}" tabindex="-1" aria-labelledby="deleteModal-{{$exam->id}}Label" aria-hidden="true">
									<div class="modal-dialog">
										<div class="modal-content">
											<form action="{{ route('exams.destroy',$exam->id) }}" method="POST" role="form">
												@csrf
												@method('DELETE')
												<div class="modal-header">
													<h5 class="modal-title" id="deleteModal-{{$exam->id}}Label">Delete</h5>
													<button type="button" class="close" data-dismiss="modal" aria-label="Close">
														<span aria-hidden="true">&times;</span>
													</button>
												</div>
												<div class="modal-body">
													<b>{{ $exam->name }}</b><br> Are you sure?

												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
													<button type="submit" class="btn btn-danger">Delete</button>
												</div>
											</form>
										</div>
									</div>
								</div>

							</div>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			{{ $exams->links() }}

			@else
			
			<div class="alert alert-warning">
				<strong>Oops!</strong> There are no records to show at the moment.
			</div>

			@endif



		</div>
	</div>
</div>
@endsection

resources/views/exam/show.blade.php
@extends('home')
@section('content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ $exam->name }} Questions</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('exams.index') }}">Exams</a></li>
            <li class="breadcrumb-item active">{{ $exam->name }}</li>
        </ol>
    </div>
</main>
<div class="container-fluid">
	<div class="card">
		<h5 class="card-header">
			Questions <a href="{{ route('questions.create',['exam'=>$exam->id]) }}" class="btn btn-info btn-sm float-right">Create question <i class="fa fa-plus"></i></a>
		</h5>
		<div class="card-body">
			
			@if($questions->count())

			<table class="table table-hover table-bordered">
				<thead class="thead-dark">
					<tr>
						<th scope="col">Question</th>
						<th scope="col" class="text-right">Options</th>
					</tr>
				</thead>
				<tbody>
					@foreach($questions as $question)
					<tr>
						<td>{{ $question->question }}</td>
						<td>
							<div class="float-right">
							<a href="{{ route('questions.edit',$question->id) }}" class="btn btn-sm btn-success">
								Edit <i class="fa fa-edit"></i>
							</a>
							| 
							<form style="display: inline-block;" action="{{ route('questions.destroy',$question->id) }}" method="POST" role="form">
								@csrf
								<input type="hidden" name="_method" value="DELETE">
								<button type="submit" class="btn btn-sm btn-danger">Delete <i class="fa fa-times"></i></button>
							</form>
							</div>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			{{ $questions->links() }}

			@else
			
			<div class="alert alert-warning">
				<strong>Oops!</strong> There are no records to show at the moment.
			</div>

			@endif

		</div>
	</div>
</div>
@endsection